branch-defaults:
  default:
    environment: accelHack
    group_suffix: null
global:
  application_name: accelhack
  branch: null
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: ap-south-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
