# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('platform', models.CharField(max_length=16)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('genre', models.CharField(max_length=17)),
                ('editors_choice', models.CharField(max_length=1)),
            ],
        ),
    ]
