# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-29 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_favourite',
            field=models.BooleanField(default='FALSE', max_length=5),
            preserve_default=False,
        ),
    ]
