# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameSearch', '0002_game_is_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='favourites',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameSearch.Game'),
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
