# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameSearch', '0005_auto_20170330_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='game',
            field=models.CharField(max_length=4),
        ),
    ]
